### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by ylboerner** [gematik/spec-ISiP#94]
- [ ] SUSHI Version erhöhen
- [ ] Validierungsfehler prüfen
- [ ] Use slice name instead of numeric index access
- [ ] Fix eventual errors
```[tasklist]
### Tasks
- [ ] PTDATA-700
```
